### ISSUE TITLE
Errors encountered while running tests aren't included in failure output

### ISSUE THREAD

**Issue by akhaku** [michaelleeallen/mocha-junit-reporter#15]
Let's say the javascript code I'm testing throws an uncaught error during execution. This causes the test to fail, as expected, and it's logged as a failure in the reporter's generated file.
However, it seems other reporters (I'm looking at xunit, specifically) include the details of the failure in the failure xml (example below) while mocha-junit-reporter leaves "failure" blanks:

**xunit**

    <testcase classname="TheName _hasNonGlobalServerErrors" name="ignores global errors" time="NaN" message=""><failure classname="TheName _hasNonGlobalServerErrors" name="ignores global errors" time="NaN" message=""><![CDATA[Error
    at React.createClass._hasNonGlobalServerErrors (/snipped/fileName.js:128:17)
    at Context.&lt;anonymous&gt; (/snipped/fileName.js:82:24)
    at Test.Runnable.run (/snipped/node_modules/mocha/lib/runnable.js:213:32)
    at Runner.runTest (/snipped/node_modules/mocha/lib/runner.js:344:10)
    at /snipped/node_modules/mocha/lib/runner.js:390:12
    at next (/snipped/node_modules/mocha/lib/runner.js:270:14)
    at /snipped/node_modules/mocha/lib/runner.js:279:7
    at next (/snipped/node_modules/mocha/lib/runner.js:227:23)
    at Immediate._onImmediate (/snipped/node_modules/mocha/lib/runner.js:247:5)
    at processImmediate [as _immediateCallback] (timers.js:358:17)]]></failure></testcase>

**mocha-junit-reporter**

    <testcase name="TheName _hasNonGlobalServerErrors ignores global errors" time="0" className="ignores global errors">
      <failure></failure>
    </testcase>

**Comment by akhaku** [comment]
Merged in #19
