### ISSUE TITLE
Weird behavior of nested suites in xml output

### ISSUE THREAD

**Issue by DanaGoyette** [michaelleeallen/mocha-junit-reporter#161]
I'm testing out the junit reporter with Cypress, and there are some weird behaviors with regards to the root suite, especially when using nested suites.

The root suite seems to be empty, and ends up being named `` (empty string) even if I have set `rootSuiteName`.  This seems to be because `fullSuiteTitle()` assumes the passed-in suite is not the root itself: `var title = [ suite.title ];`

If I set  `useFullSuiteTitle` to `true`, there's no way to omit the root name, because the `||` operator overrides the empty string:  
```
config.rootSuiteTitle = config.rootSuiteTitle || 'Root Suite';
config.testsuitesTitle = config.testsuitesTitle || 'Mocha Tests';
```

Given this sample test:
```typescript
context('Outer1', () => {
  context('InnerA', () => {
    it('Bad', () => { expect(false).to.be.true })
    it('Good', () => {})
    xit('Pending', () => {})
  })
  context('InnerB', () => {
    it('Bad', () => { expect(false).to.be.true })
    it('Good', () => {})
    xit('Pending', () => {})
  })
})
context('Outer2', () => {
  context('InnerA', () => {
    it('Bad', () => { expect(false).to.be.true })
    it('Good', () => {})
    xit('Pending', () => {})
  })
  context('InnerB', () => {
    it('Bad', () => { expect(false).to.be.true })
    it('Good', () => {})
    xit('Pending', () => {})
  })
})
```

Assuming the config:
```json
{
  "testCaseSwitchClassnameAndName": true,
  "useFullSuiteTitle": true,
  "suiteTitleSeparatedBy": " -- ",
  "rootSuiteTitle": ""
}
```

What I expect (though the last piece of the classname is redundant): 
```xml
<testsuite name="Outer1 -- InnerA" tests="3">
    <testcase name="Bad" classname="Outer1 -- InnerA -- Bad">…</testcase>
<testsuite>
```

What I get: 
```xml
<testsuite name="" tests="0">
</testsuite>
<testsuite name="Root Suite -- Outer1 -- InnerA" tests="3">
    <testcase name="Bad" classname="Root Suite Outer1 InnerA">…</testcase>
</testsuite>
```

Full spew, with `"testCaseSwitchClassnameAndName": true`: 
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="1.1380" tests="12" failures="4" skipped="4">
  <testsuite name="" timestamp="2022-02-03T01:13:51" tests="0" file="cypress/integration/sample.test.ts" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="Root Suite -- Outer1" timestamp="2022-02-03T01:13:51" tests="0" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="Root Suite -- Outer1 -- InnerA" timestamp="2022-02-03T01:13:51" tests="3" time="0.2290" failures="1">
    <testcase name="Bad" time="0.0000" classname="Outer1 InnerA Bad">
      <failure message="expected false to be true" type="AssertionError"><![CDATA[AssertionError: expected false to be true
    at Context.eval (http://localhost:3001/__cypress/tests?p=cypress/integration/sample.test.ts:98:52)]]></failure>
    </testcase>
    <testcase name="Good" time="0.0290" classname="Outer1 InnerA Good">
    </testcase>
  </testsuite>
  <testsuite name="Root Suite -- Outer1 -- InnerB" timestamp="2022-02-03T01:13:51" tests="3" time="0.2310" failures="1">
    <testcase name="Bad" time="0.0000" classname="Outer1 InnerB Bad">
      <failure message="expected false to be true" type="AssertionError"><![CDATA[AssertionError: expected false to be true
    at Context.eval (http://localhost:3001/__cypress/tests?p=cypress/integration/sample.test.ts:104:32)]]></failure>
    </testcase>
    <testcase name="Good" time="0.0240" classname="Outer1 InnerB Good">
    </testcase>
  </testsuite>
  <testsuite name="Root Suite -- Outer2" timestamp="2022-02-03T01:13:52" tests="0" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="Root Suite -- Outer2 -- InnerA" timestamp="2022-02-03T01:13:52" tests="3" time="0.2290" failures="1">
    <testcase name="Bad" time="0.0000" classname="Outer2 InnerA Bad">
      <failure message="expected false to be true" type="AssertionError"><![CDATA[AssertionError: expected false to be true
    at Context.eval (http://localhost:3001/__cypress/tests?p=cypress/integration/sample.test.ts:112:52)]]></failure>
    </testcase>
    <testcase name="Good" time="0.0260" classname="Outer2 InnerA Good">
    </testcase>
  </testsuite>
  <testsuite name="Root Suite -- Outer2 -- InnerB" timestamp="2022-02-03T01:13:52" tests="3" time="0.2880" failures="1">
    <testcase name="Bad" time="0.0000" classname="Outer2 InnerB Bad">
      <failure message="expected false to be true" type="AssertionError"><![CDATA[AssertionError: expected false to be true
    at Context.eval (http://localhost:3001/__cypress/tests?p=cypress/integration/sample.test.ts:117:52)]]></failure>
    </testcase>
    <testcase name="Good" time="0.0280" classname="Outer2 InnerB Good">
    </testcase>
  </testsuite>
</testsuites>
```

Full spew, with `"testCaseSwitchClassnameAndName": false`: 
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="1.1570" tests="12" failures="4" skipped="4">
  <testsuite name="Root Suite" timestamp="2022-02-03T01:14:37" tests="0" file="cypress/integration/sample.test.ts" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="Outer1" timestamp="2022-02-03T01:14:38" tests="0" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="InnerA" timestamp="2022-02-03T01:14:38" tests="3" time="0.2420" failures="1">
    <testcase name="Bad" time="0.0000" classname="Outer1 InnerA Bad">
      <failure message="expected false to be true" type="AssertionError"><![CDATA[AssertionError: expected false to be true
    at Context.eval (http://localhost:3001/__cypress/tests?p=cypress/integration/sample.test.ts:98:52)]]></failure>
    </testcase>
    <testcase name="Good" time="0.0270" classname="Outer1 InnerA Good">
    </testcase>
  </testsuite>
  <testsuite name="InnerB" timestamp="2022-02-03T01:14:38" tests="3" time="0.2220" failures="1">
    <testcase name="Bad" time="0.0000" classname="Outer1 InnerB Bad">
      <failure message="expected false to be true" type="AssertionError"><![CDATA[AssertionError: expected false to be true
    at Context.eval (http://localhost:3001/__cypress/tests?p=cypress/integration/sample.test.ts:104:32)]]></failure>
    </testcase>
    <testcase name="Good" time="0.0220" classname="Outer1 InnerB Good">
    </testcase>
  </testsuite>
  <testsuite name="Outer2" timestamp="2022-02-03T01:14:38" tests="0" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="InnerA" timestamp="2022-02-03T01:14:38" tests="3" time="0.2300" failures="1">
    <testcase name="Bad" time="0.0000" classname="Outer2 InnerA Bad">
      <failure message="expected false to be true" type="AssertionError"><![CDATA[AssertionError: expected false to be true
    at Context.eval (http://localhost:3001/__cypress/tests?p=cypress/integration/sample.test.ts:112:52)]]></failure>
    </testcase>
    <testcase name="Good" time="0.0270" classname="Outer2 InnerA Good">
    </testcase>
  </testsuite>
  <testsuite name="InnerB" timestamp="2022-02-03T01:14:38" tests="3" time="0.3020" failures="1">
    <testcase name="Bad" time="0.0000" classname="Outer2 InnerB Bad">
      <failure message="expected false to be true" type="AssertionError"><![CDATA[AssertionError: expected false to be true
    at Context.eval (http://localhost:3001/__cypress/tests?p=cypress/integration/sample.test.ts:117:52)]]></failure>
    </testcase>
    <testcase name="Good" time="0.0340" classname="Outer2 InnerB Good">
    </testcase>
  </testsuite>
</testsuites>
```

**Comment by babalubas090** [comment]
I'm having the same issue here

**Comment by louneskmt** [comment]
Same here

**Comment by cgraham-rs** [comment]
Being unable to lose the `rootSuiteName` makes for some ugly and unnecessary text if you're outputting XML to be imported into something like TestRail.

<img width="486" alt="image" src="https://github.com/michaelleeallen/mocha-junit-reporter/assets/87026636/d5484c8e-25f3-4197-a166-52d32c446b8b">

**Comment by Radiergummi** [comment]
This issue makes the reporter almost useless for us, because tests aren't even grouped under their file.

**Comment by nikolaos-papandreou** [comment]
Have you found any solution or alternatives for this? If not we will have to ditch this reporter.

**Comment by DanaGoyette** [comment]
It's been a while (I ran into this at a previous job), but I ended up making a copy of the reporter and fixing how it reported the tests.  Unfortunately, I don't remember exactly what I changed, I wish I'd saved a diff of it.

I wonder if any of the forks of this plugin improve things?  But I can't vouch for any of the forks in particular.
