### ISSUE TITLE
Cannot read property 'testsuite' of undefined

### ISSUE THREAD

**Issue by Aditya18Jain** [michaelleeallen/mocha-junit-reporter#68]
/home/aditya/Desktop/pycom/node_modules/mocha-junit-reporter/index.js:106
    return testsuites[testsuites.length - 1].testsuite;
                                             ^

TypeError: Cannot read property 'testsuite' of undefined
    at lastSuite (/home/aditya/Desktop/pycom/node_modules/mocha-junit-reporter/index.js:106:46)
    at MochaJUnitReporter.<anonymous> (/home/aditya/Desktop/pycom/node_modules/mocha-junit-reporter/index.js:131:5)
    at emitTwo (events.js:131:20)
    at Runner.emit (events.js:214:7)
    at Runner.fail (/home/aditya/Desktop/pycom/pybytes-react/node_modules/mocha/lib/runner.js:239:8)
    at Runner.uncaught (/home/aditya/Desktop/pycom/pybytes-react/node_modules/mocha/lib/runner.js:716:12)
    at process.uncaught (/home/aditya/Desktop/pycom/pybytes-react/node_modules/mocha/lib/runner.js:821:10)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at process._fatalException (bootstrap_node.js:378:26)

**Comment by jasonk** [comment]
Try running your tests with `DEBUG=mocha*` set.  I was getting this same error and discovered that there was an error being thrown in some of my test setup code that was getting hidden.  I'm not sure if it was `mocha-junit-reporter` that was hiding it or not (it might have been `mocha-multi`), but that helped lead me in the right direction..

**Comment by soryy708** [comment]
I've run with `DEBUG=mocha*` and seen that the error in my case was caused by trying to treat a folder as a file. Specifically, `mochaFile` was a folder.

@Aditya18Jain What do you get when you run with `DEBUG=mocha*`?

**Comment by clayreimann** [comment]
Closing as stale

**Comment by mparkhomenko** [comment]
@soryy708 Did you solve this?

**Comment by akhild1205** [comment]
any idea how to resolve this. for me its still causing the problem
