### ISSUE TITLE
runner.on is not a function

### ISSUE THREAD

**Issue by MuhammadBilalYar** [michaelleeallen/mocha-junit-reporter#69]
I am trying to run this command `--reporter=mocha-junit-reporter  mochaFile=./TestResults/TEST-RESULT.xml`
and then it through error **TypeError: runner.on is not a function**

```
D:\............\node_modules\nyc\node_modules\yargs\yargs.js:1133
      else throw err
           ^

TypeError: runner.on is not a function
    at MochaJUnitReporter.Base (D:\............\node_modules\mocha\lib\reporters\base.js:267:10)
    at new MochaJUnitReporter (D:\............\node_modules\mocha-junit-reporter\index.js:110:8)
    at Object.create (D:\............\node_modules\nyc\node_modules\istanbul-reports\index.js:17:16)
    at reporter.forEach (D:\............\node_modules\nyc\index.js:459:24)
    at Array.forEach (<anonymous>)
    at NYC.report (D:\............\node_modules\nyc\index.js:458:17)
    at Object.exports.handler (D:\............\node_modules\nyc\lib\commands\report.js:44:7)
    at Object.runCommand (D:\............\node_modules\nyc\node_modules\yargs\lib\command.js:235:44)
    at Object.parseArgs [as _parseArgs] (D:\............\node_modules\nyc\node_modules\yargs\yargs.js:1046:30)
    at Object.parse (D:\............\node_modules\nyc\node_modules\yargs\yargs.js:551:25)
npm ERR! Test failed.  See above for more details.
```

**Comment by clayreimann** [comment]
Can you provide a sample project that reproduce the issue? I just did a cursory scan of the mocha change log and they still refer to `runner.on` in their version 5 changes

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MuhammadBilalYar** [comment]
Sorry, Due to some security policies I can't share project. But I resolved the issue.

**Comment by clayreimann** [comment]
Glad you found the cause of your issue

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
