### ISSUE TITLE
junit-reporter does not support mocha 6

### ISSUE THREAD

**Issue by IdanAdar** [michaelleeallen/mocha-junit-reporter#78]
Whenever attempting to use this reporter with the latest mocha, mocha fails. With previous releases of mocha, it did not.

**Comment by DavidBurela** [comment]
Experiencing the same issue. Pinning to mocha 5.2.0 works, but using 6.0.x results in a failure

**Comment by dmitriy-kurochkin** [comment]
Same problem here
```
$ codeceptjs run --reporter mocha-junit-reporter
TypeError: Cannot read property 'failures' of undefined
TypeError: Cannot read property 'failures' of undefined
    at MochaJUnitReporter.getXml (/Users/dmitriy.kurochkin/project/node_modules/mocha-junit-reporter/index.js:291:23)
    at MochaJUnitReporter.flush (/Users/dmitriy.kurochkin/project/node_modules/mocha-junit-reporter/index.js:238:18)
    at MochaJUnitReporter.<anonymous> (/Users/dmitriy.kurochkin/project/node_modules/mocha-junit-reporter/index.js:144:10)
    at Runner.emit (events.js:202:15)
    at /Users/dmitriy.kurochkin/project/node_modules/codeceptjs/node_modules/mocha/lib/runner.js:829:12
    at /Users/dmitriy.kurochkin/project/node_modules/codeceptjs/node_modules/mocha/lib/runner.js:677:9
    at next (/Users/dmitriy.kurochkin/project/node_modules/codeceptjs/node_modules/mocha/lib/runner.js:290:14)
    at Immediate.<anonymous> (/Users/dmitriy.kurochkin/project/node_modules/codeceptjs/node_modules/mocha/lib/runner.js:334:5)
    at processImmediate (timers.js:637:19)
error Command failed with exit code 1.
```

**Comment by YOU54F** [comment]
Hi,

I have 2 PR's tracking this upgrade to mocha 6, I use cypress & mochawesome for reporting.

They have circleci runs associated with them, in case anyone wants to track the change as the other dependancies update. I haven't had a chance to look into this yet in much detail

https://github.com/YOU54F/cypressio-docker-typescript/pull/15
https://github.com/YOU54F/cypressio-docker/pull/12

**Comment by YOU54F** [comment]
Just fixed this and proposed the following 2 PR's

https://github.com/stanleyhlng/mocha-multi-reporters/pull/58
https://github.com/michaelleeallen/mocha-junit-reporter/pull/80

My branch tracking the changes, with failing builds with mocha 6 pre and post fix is here

https://github.com/YOU54F/cypressio-docker-typescript/pull/15/files

If you do want to move up to mocha 6, you can pull my forked branch in the interim, whilst we wait for the maintainers of the source repo to review/merge/release the PR

```
    "mocha": "^6.0.0",
    "mocha-junit-reporter": "YOU54F/mocha-junit-reporter#master",
    "mocha-multi-reporters": "YOU54F/mocha-multi-reporters#master",
```

**Comment by shavo007** [comment]
This config worked for me
.mocharc.json

```
{
  "diff": true,
  "extension": ["js"],
  "package": "./package.json",
  "reporter": "mocha-junit-reporter",
  "slow": 75,
  "timeout": 2000,
  "ui": "bdd",
  "reporter-option": ["mochaFile=./reports/junit.xml"],
  "require": ["@babel/register", "test/mochaSetup", "dotenv/config"],
  "spec": "./src/**/*.spec.js"
}

```

**Comment by canterberry** [comment]
:bulb: Mocha 6 now natively supports XUnit-style reports via the [`xunit` reporter](https://mochajs.org/#xunit). Rejoice!

```
# Before
mocha ... --reporter mocha-junit-reporter --reporter-options mochaFile=/path/to/output.xml

# After
mocha ... --reporter xunit --reporter-options output=/path/to/output.xml
```

This got me up and running when I ran into the snag other folks have mentioned above when using the current latest version of Mocha.

**Comment by YOU54F** [comment]
@canterberry great news :)

btw I have updated my comment above, with a released npm packages that will support mocha 6 and below. I couldn't wait for the PR to get merged and lots of people were after mocha 6 support

**Comment by YOU54F** [comment]
@IdanAdar 

This should be resolved now in this repo! 🙌

The fix for mocha-junit-reporter has now been merged and is available in the newly released v1.23.0

https://github.com/michaelleeallen/mocha-junit-reporter/releases/tag/v1.23.0

**Comment by IdanAdar** [comment]
Has anyone got this to work (with `mocha: ^6.0.0`)?

package.json
```
"test": "jenkins-mocha --recursive --reporter mocha-multi-reporters --reporter-options configFile=config/mocha-config.json --exit",
```

mocha-config.json
```
{
   "reporterEnabled": "list,mocha-junit-reporter",
    "mochaJunitReporterReporterOptions": {
	"mochaFile": "testResults/results.xml"
    }
}
```

This combination fails with (while using v1.23.0 of `mocha-junit-reporter`):
```
[2019-06-10T02:58:57.631Z] [FATAL] appBase - Unhandled exception happened! Error message: Cannot read property 'passes' of undefined
{}
TypeError: Cannot read property 'passes' of undefined
    at List.Base.epilogue (/Users/iadar/Documents/***/node_modules/mocha/lib/reporters/base.js:319:26)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at Runner.emit (events.js:208:7)
    at /Users/iadar/***/node_modules/jenkins-mocha/node_modules/mocha/lib/runner.js:829:12
    at /Users/iadar/***/node_modules/jenkins-mocha/node_modules/mocha/lib/runner.js:677:9
    at next (/Users/iadar/***/node_modules/jenkins-mocha/node_modules/mocha/lib/runner.js:290:14)
    at Immediate._onImmediate (/Users/iadar/***/node_modules/jenkins-mocha/node_modules/mocha/lib/runner.js:334:5)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5) - instanceId: SystemId
  1) *** - *** "after each" hook
```

If I replace `mocha-junit-reporter` in the JSON file with the suggested `xunit`, it fails with the same as above and then also this:

```
/Users/iadar/Documents/Bluemix/GitHub/certificate-management-service-api/node_modules/mocha/lib/reporters/xunit.js:94
          tests: stats.tests,
                       ^

TypeError: Cannot read property 'tests' of undefined
    at Runner.<anonymous> (/Users/iadar/***/node_modules/mocha/lib/reporters/xunit.js:94:24)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at Runner.emit (events.js:208:7)
    at /Users/iadar/***/node_modules/jenkins-mocha/node_modules/mocha/lib/runner.js:829:12
    at done (/Users/iadar/***/node_modules/jenkins-mocha/node_modules/mocha/lib/runner.js:666:7)
    at next (/Users/iadar/***/node_modules/jenkins-mocha/node_modules/mocha/lib/runner.js:633:16)
    at done (/Users/iadar/***/node_modules/jenkins-mocha/node_modules/mocha/lib/runner.js:666:7)
    at next (/Users/iadar/***/node_modules/jenkins-mocha/node_modules/mocha/lib/runner.js:637:14)
    at done (/Users/iadar/***/node_modules/jenkins-mocha/node_modules/mocha/lib/runner.js:666:7)
    at next (/Users/iadar/***/node_modules/jenkins-mocha/node_modules/mocha/lib/runner.js:637:14)
    at Runner.hookErr (/Users/iadar/***/node_modules/jenkins-mocha/node_modules/mocha/lib/runner.js:482:7)
    at Runner.uncaught (/Users/iadar/***/node_modules/jenkins-mocha/node_modules/mocha/lib/runner.js:747:19)
    at process.uncaught (/Users/iadar/***/node_modules/jenkins-mocha/node_modules/mocha/lib/runner.js:821:10)
    at emitOne (events.js:121:20)
    at process.emit (events.js:211:7)
    at processEmit [as emit] (/Users/iadar/***/node_modules/nyc/node_modules/signal-exit/index.js:155:32)
    at process._fatalException (bootstrap_node.js:391:26)
```

**Comment by YOU54F** [comment]
Mocha-multi-reporters still doesn’t have the fix in... 

Try using mocha-junit-reporter directly or try cypress-multi-reporters, as per my instructions as that also contains the fix

**Comment by IdanAdar** [comment]
That combination worked.

**Comment by YOU54F** [comment]
@IdanAdar cool, do you want to close this issue now?
